"""Give the lab domain controller a certificate, the way a real one has.

This container stands in for Active Directory; it is not here to test Samba. A
domain controller in the field has a certificate issued to it and installed —
from AD CS, or whatever CA the domain runs — and it keeps it. Samba out of the
box has none, so it provisions what it calls a "temporary autogenerated" one and
gives it a random serial number, which is negative about half the time. Go's
crypto/x509 rejects a negative serial (RFC 5280 says it is a positive integer),
so leaving Samba to it would mean a lab that comes up usable on a coin flip,
over a certificate no domain controller would ever actually present.

The lab issues its own instead. Still self-signed and still issued for the
container's hostname, because that part is worth keeping: connecting to
127.0.0.1 fails verification and lands on the trust-on-first-use prompt, which
is what a client meets whenever a DC's certificate comes from a CA it does not
already trust.

Runs before the domain is provisioned. Samba reads these files once at startup
and keeps them, and provisioning leaves an existing set alone.
"""

import datetime
import os

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID

TLS_DIR = "/var/lib/samba/private/tls"
HOST = os.environ.get("SAMBA_CERT_HOST", "padldc.ad.example.com")


def main():
    if os.path.exists(os.path.join(TLS_DIR, "cert.pem")):
        return

    os.makedirs(TLS_DIR, mode=0o700, exist_ok=True)

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    name = x509.Name([
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, "PADL Lab"),
        x509.NameAttribute(NameOID.ORGANIZATIONAL_UNIT_NAME, "Throwaway lab certificate"),
        x509.NameAttribute(NameOID.COMMON_NAME, HOST),
    ])
    now = datetime.datetime.now(datetime.timezone.utc)

    # The hostname is deliberately the only subject alternative name. Adding
    # 127.0.0.1 would let the certificate verify against what the tests connect
    # to, and the point is that it does not.
    cert = (
        x509.CertificateBuilder()
        .subject_name(name)
        .issuer_name(name)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - datetime.timedelta(days=1))
        .not_valid_after(now + datetime.timedelta(days=3650))
        .add_extension(
            x509.SubjectAlternativeName([x509.DNSName(HOST), x509.DNSName(HOST.split(".")[0])]),
            critical=False,
        )
        .add_extension(x509.BasicConstraints(ca=True, path_length=None), critical=True)
        .sign(key, hashes.SHA256())
    )

    pem = cert.public_bytes(serialization.Encoding.PEM)
    write(os.path.join(TLS_DIR, "key.pem"), key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.TraditionalOpenSSL,
        serialization.NoEncryption(),
    ), 0o600)
    write(os.path.join(TLS_DIR, "cert.pem"), pem, 0o644)
    # Samba wants a CA file as well; the certificate is its own issuer.
    write(os.path.join(TLS_DIR, "ca.pem"), pem, 0o644)

    print(f"padl: wrote a lab certificate for {HOST}, serial {cert.serial_number}")


def write(path, data, mode):
    with open(path, "wb") as f:
        f.write(data)
    os.chmod(path, mode)


if __name__ == "__main__":
    main()
